FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/merchant-web/package.json ./apps/merchant-web/

RUN bun install

COPY . .

EXPOSE 4200

CMD ["bun", "run", "--filter", "merchant-web", "start"]
